name: Generar números aleatorios

on:
  schedule:
    - cron: "0,15,30,45 * * * *"  # ejecucion cada 15 minutos
  workflow_dispatch:  # Permitir ejecución manual

permissions:
  contents: write  # Permite que GitHub Actions escriba en los contenidos del repositorio

jobs:
  generate-numbers:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Generar número y guardar
      run: |
        python prueba.py

    - name: Configurar Git para Commit
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
    - name: Commit y Push cambios
      run: |
        git add numeros_aleatorios.txt
        git commit -m "Actualizar números aleatorios"
        git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
