name: Generar números aleatorios

on:
  schedule:
    - cron: "*/1 * * * *"  # Ejecutar cada 5 minutos para prueba inicial
  workflow_dispatch:  # Permite la ejecución manual desde la interfaz de GitHub

jobs:
  generate-numbers:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Generar número y guardar
      run: |
        python prueba.py

    - name: Commit de los cambios
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add numeros_aleatorios.txt
        git commit -m "Actualizar números aleatorios"
        git push
