name: Reserva Automática Parkalot

on:
  schedule:
    - cron: '0 19 * * 1-5' # 19 UTC = 16 ART, lunes a viernes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Instalar Chromium para Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar script de reserva
        run: node index.js
        env:
          MY_EMAIL: ${{ secrets.PARKALOT_EMAIL }}
          MY_PASSWORD: ${{ secrets.PARKALOT_PASSWORD }}
